"""empty message

Revision ID: 3a97dc75ec5a
Revises: 9427db3b9bfa
Create Date: 2020-05-05 03:14:03.878600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a97dc75ec5a'
down_revision = '9427db3b9bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('Album', sa.String(length=100), nullable=True))
    op.add_column('playlist', sa.Column('Artist', sa.String(length=100), nullable=True))
    op.add_column('playlist', sa.Column('prevIMG', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'prevIMG')
    op.drop_column('playlist', 'Artist')
    op.drop_column('playlist', 'Album')
    # ### end Alembic commands ###
