"""empty message

Revision ID: 75fcbd4063f6
Revises: d69cf8c261e0
Create Date: 2020-05-05 04:02:20.234247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fcbd4063f6'
down_revision = 'd69cf8c261e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('songID', sa.VARCHAR(length=100), nullable=True),
    sa.Column('prevURL', sa.VARCHAR(length=100), nullable=True),
    sa.Column('songName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Album', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Artist', sa.VARCHAR(length=100), nullable=True),
    sa.Column('prevIMG', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
