"""empty message

Revision ID: 9427db3b9bfa
Revises: 8c9eccc573dc
Create Date: 2020-05-03 01:09:06.659662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9427db3b9bfa'
down_revision = '8c9eccc573dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('songName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'songName')
    # ### end Alembic commands ###
