"""empty message

Revision ID: ae12af881220
Revises: 75fcbd4063f6
Create Date: 2020-05-05 04:02:46.148671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae12af881220'
down_revision = '75fcbd4063f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('songID', sa.String(length=100), nullable=True),
    sa.Column('prevURL', sa.String(length=100), nullable=True),
    sa.Column('prevIMG', sa.String(length=100), nullable=True),
    sa.Column('songName', sa.String(length=100), nullable=True),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('album', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist')
    # ### end Alembic commands ###
