"""empty message

Revision ID: c8f5f71e6a03
Revises: 3a97dc75ec5a
Create Date: 2020-05-05 03:22:26.455589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f5f71e6a03'
down_revision = '3a97dc75ec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return 'ok'
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('Album', sa.VARCHAR(length=100), nullable=True))
    op.add_column('playlist', sa.Column('Artist', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('playlist', 'artist')
    op.drop_column('playlist', 'album')
    # ### end Alembic commands ###
