"""empty message

Revision ID: d69cf8c261e0
Revises: c8f5f71e6a03
Create Date: 2020-05-05 04:00:23.873443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69cf8c261e0'
down_revision = 'c8f5f71e6a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return 'ok'
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('Album', sa.VARCHAR(length=100), nullable=True))
    op.add_column('playlist', sa.Column('Artist', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('playlist', 'artist')
    op.drop_column('playlist', 'album')
    # ### end Alembic commands ###
